# Lab 5 Tasks

## Task 1 - JSON Parsing

Use Python to download a file containing movie metadata in JSON format from the URL: http://mlg.ucd.ie/modules/COMP30760/movies.json

In [3]:
import urllib.request
url = "http://mlg.ucd.ie/modules/COMP30760/movies.json"
response = urllib.request.urlopen(url)
raw_json = response.read().decode("utf-8")
print(raw_json)

[{
	"Title": "London Has Fallen",
	"Year": "2016",
	"Rated": "R",
	"Runtime": "99 min",
	"Genre": "Action, Crime, Thriller",
	"Director": "Babak Najafi",
	"Actors": "Gerard Butler, Morgan Freeman, Charlotte Riley, Angela Bassett",
	"Country": "UK, USA, Bulgaria",
	"RatingScore": "28",
	"Type": "movie"
}, {
	"Title": "Deadpool",
	"Year": "2016",
	"Rated": "R",
	"Runtime": "108 min",
	"Genre": "Action, Adventure, Comedy",
	"Director": "Tim Miller",
	"Actors": "Ryan Reynolds, Karan Soni, Ed Skrein, Michael Benyaer",
	"Country": "USA, Canada",
	"RatingScore": "65",
	"Type": "movie"
}, {
	"Title": "Kung Fu Panda 3",
	"Year": "2016",
	"Rated": "PG",
	"Runtime": "95 min",
	"Genre": "Animation, Action, Adventure",
	"Director": "Alessandro Carloni, Jennifer Yuh",
	"Actors": "Jack Black, Bryan Cranston, Dustin Hoffman, Angelina Jolie",
	"Country": "China, USA",
	"RatingScore": "64",
	"Type": "movie"
}, {
	"Title": "Spectre",
	"Year": "2015",
	"Rated": "PG-13",
	"Runtime": "148 min",
	"Genre": "Action, Adventure, Thriller",
	"Director": "Sam Mendes",
	"Actors": "Daniel Craig, Christoph Waltz, Léa Seydoux, Ralph Fiennes",
	"Country": "UK, USA",
	"RatingScore": "60",
	"Type": "movie"
}, {
	"Title": "Brooklyn",
	"Year": "2015",
	"Rated": "PG-13",
	"Runtime": "111 min",
	"Genre": "Drama, Romance",
	"Director": "John Crowley",
	"Actors": "Saoirse Ronan, Hugh Gormley, Brid Brennan, Jim Broadbent",
	"Country": "Ireland, UK, Canada",
	"RatingScore": "87",
	"Type": "movie"
}, {
	"Title": "The Revenant",
	"Year": "2015",
	"Rated": "R",
	"Runtime": "156 min",
	"Genre": "Adventure, Drama, Thriller",
	"Director": "Alejandro González Iñárritu",
	"Actors": "Leonardo DiCaprio, Tom Hardy, Domhnall Gleeson, Will Poulter",
	"Country": "USA",
	"RatingScore": "76",
	"Type": "movie"
}, {
	"Title": "1917",
	"Year": "2019",
	"Rated": "R",
	"Runtime": "119 min",
	"Genre": "Drama, War",
	"Director": "Sam Mendes",
	"Actors": "Dean-Charles Chapman, George MacKay, Daniel Mays, Colin Firth",
	"Country": "USA",
	"RatingScore": "78",
	"Type": "movie"
}, {
	"Title": "Joker",
	"Year": "2019",
	"Rated": "R",
	"Runtime": "122 min",
	"Genre": "Crime, Drama, Thriller",
	"Director": "Todd Phillips",
	"Actors": "Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy",
	"Country": "USA",
	"RatingScore": "59",
	"Type": "movie"
}, {
	"Title": "Uncut Gems",
	"Year": "2019",
	"Rated": "R",
	"Runtime": "135 min",
	"Genre": "Crime, Drama, Thriller",
	"Director": "Benny Safdie, Josh Safdie",
	"Actors": "Mesfin Lamengo, Sun Zhi Hua-Hilton, Liang Wei-Hui-Duncan, Sunny Wu Jin Zahao",
	"Country": "USA",
	"RatingScore": "90",
	"Type": "movie"
}, {
	"Title": "Knives Out",
	"Year": "2019",
	"Rated": "PG-13",
	"Runtime": "131 min",
	"Genre": "Comedy, Crime, Drama, Mystery, Thriller",
	"Director": "Rian Johnson",
	"Actors": "Daniel Craig, Chris Evans, Ana de Armas, Jamie Lee Curtis",
	"Country": "USA",
	"RatingScore": "82",
	"Type": "movie"
}, {
	"Title": "Jumanji: The Next Level",
	"Year": "2019",
	"Director": "Jake Kasdan",
	"Rated": "PG-13",
	"Runtime": "123 min",
	"Genre": "Action, Adventure, Comedy, Fantasy",
	"Actors": "Dwayne Johnson, Kevin Hart, Jack Black, Karen Gillan",
	"Country": "USA",
	"RatingScore": "58",
	"Type": "movie"
}, {
	"Title": "Venom",
	"Year": "2018",
	"Rated": "PG-13",
	"Runtime": "112 min",
	"Genre": "Action, Sci-Fi, Thriller",
	"Director": "Ruben Fleischer",
	"Actors": "Tom Hardy, Michelle Williams, Riz Ahmed, Scott Haze",
	"Country": "China, USA",
	"RatingScore": "35",
	"Type": "movie"
}, {
	"Title": "Incredibles 2",
	"Year": "2018",
	"Rated": "PG",
	"Runtime": "118 min",
	"Genre": "Animation, Action, Adventure, Comedy, Family, Sci-Fi",
	"Director": "Brad Bird",
	"Country": "USA",
	"Actors": "Craig T. Nelson, Holly Hunter, Sarah Vowell, Huck Milner",
	"RatingScore": "80",
	"Type": "movie"
}, {
	"Title": "Suspiria",
	"Year": "2018",
	"Rated": "R",
	"Runtime": "152 min",
	"Genre": "Fantasy, Horror, Mystery, Thriller",
	"Director": "Luca Guadagnino",
	"Actors": "Chloë Grace Moretz, Tilda Swinton, Doris Hick, Malgorzata Bela",
	"Country": "Italy, USA",
	"RatingScore": "64",
	"Type": "movie"
}, {
	"Title": "A Quiet Place",
	"Year": "2018",
	"Rated": "PG-13",
	"Runtime": "90 min",
	"Genre": "Drama, Horror, Sci-Fi",
	"Director": "John Krasinski",
	"Actors": "Emily Blunt, John Krasinski, Millicent Simmonds, Noah Jupe",
	"Country": "USA",
	"RatingScore": "82",
	"Type": "movie"
}]

Parse the JSON data that you have downloaded.

In [5]:
import json 
data = json.loads(raw_json)
for movie in data:
    print(movie)

{'Title': 'London Has Fallen', 'Year': '2016', 'Rated': 'R', 'Runtime': '99 min', 'Genre': 'Action, Crime, Thriller', 'Director': 'Babak Najafi', 'Actors': 'Gerard Butler, Morgan Freeman, Charlotte Riley, Angela Bassett', 'Country': 'UK, USA, Bulgaria', 'RatingScore': '28', 'Type': 'movie'}
{'Title': 'Deadpool', 'Year': '2016', 'Rated': 'R', 'Runtime': '108 min', 'Genre': 'Action, Adventure, Comedy', 'Director': 'Tim Miller', 'Actors': 'Ryan Reynolds, Karan Soni, Ed Skrein, Michael Benyaer', 'Country': 'USA, Canada', 'RatingScore': '65', 'Type': 'movie'}
{'Title': 'Kung Fu Panda 3', 'Year': '2016', 'Rated': 'PG', 'Runtime': '95 min', 'Genre': 'Animation, Action, Adventure', 'Director': 'Alessandro Carloni, Jennifer Yuh', 'Actors': 'Jack Black, Bryan Cranston, Dustin Hoffman, Angelina Jolie', 'Country': 'China, USA', 'RatingScore': '64', 'Type': 'movie'}
{'Title': 'Spectre', 'Year': '2015', 'Rated': 'PG-13', 'Runtime': '148 min', 'Genre': 'Action, Adventure, Thriller', 'Director': 'Sam Mendes', 'Actors': 'Daniel Craig, Christoph Waltz, Léa Seydoux, Ralph Fiennes', 'Country': 'UK, USA', 'RatingScore': '60', 'Type': 'movie'}
{'Title': 'Brooklyn', 'Year': '2015', 'Rated': 'PG-13', 'Runtime': '111 min', 'Genre': 'Drama, Romance', 'Director': 'John Crowley', 'Actors': 'Saoirse Ronan, Hugh Gormley, Brid Brennan, Jim Broadbent', 'Country': 'Ireland, UK, Canada', 'RatingScore': '87', 'Type': 'movie'}
{'Title': 'The Revenant', 'Year': '2015', 'Rated': 'R', 'Runtime': '156 min', 'Genre': 'Adventure, Drama, Thriller', 'Director': 'Alejandro González Iñárritu', 'Actors': 'Leonardo DiCaprio, Tom Hardy, Domhnall Gleeson, Will Poulter', 'Country': 'USA', 'RatingScore': '76', 'Type': 'movie'}
{'Title': '1917', 'Year': '2019', 'Rated': 'R', 'Runtime': '119 min', 'Genre': 'Drama, War', 'Director': 'Sam Mendes', 'Actors': 'Dean-Charles Chapman, George MacKay, Daniel Mays, Colin Firth', 'Country': 'USA', 'RatingScore': '78', 'Type': 'movie'}
{'Title': 'Joker', 'Year': '2019', 'Rated': 'R', 'Runtime': '122 min', 'Genre': 'Crime, Drama, Thriller', 'Director': 'Todd Phillips', 'Actors': 'Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy', 'Country': 'USA', 'RatingScore': '59', 'Type': 'movie'}
{'Title': 'Uncut Gems', 'Year': '2019', 'Rated': 'R', 'Runtime': '135 min', 'Genre': 'Crime, Drama, Thriller', 'Director': 'Benny Safdie, Josh Safdie', 'Actors': 'Mesfin Lamengo, Sun Zhi Hua-Hilton, Liang Wei-Hui-Duncan, Sunny Wu Jin Zahao', 'Country': 'USA', 'RatingScore': '90', 'Type': 'movie'}
{'Title': 'Knives Out', 'Year': '2019', 'Rated': 'PG-13', 'Runtime': '131 min', 'Genre': 'Comedy, Crime, Drama, Mystery, Thriller', 'Director': 'Rian Johnson', 'Actors': 'Daniel Craig, Chris Evans, Ana de Armas, Jamie Lee Curtis', 'Country': 'USA', 'RatingScore': '82', 'Type': 'movie'}
{'Title': 'Jumanji: The Next Level', 'Year': '2019', 'Director': 'Jake Kasdan', 'Rated': 'PG-13', 'Runtime': '123 min', 'Genre': 'Action, Adventure, Comedy, Fantasy', 'Actors': 'Dwayne Johnson, Kevin Hart, Jack Black, Karen Gillan', 'Country': 'USA', 'RatingScore': '58', 'Type': 'movie'}
{'Title': 'Venom', 'Year': '2018', 'Rated': 'PG-13', 'Runtime': '112 min', 'Genre': 'Action, Sci-Fi, Thriller', 'Director': 'Ruben Fleischer', 'Actors': 'Tom Hardy, Michelle Williams, Riz Ahmed, Scott Haze', 'Country': 'China, USA', 'RatingScore': '35', 'Type': 'movie'}
{'Title': 'Incredibles 2', 'Year': '2018', 'Rated': 'PG', 'Runtime': '118 min', 'Genre': 'Animation, Action, Adventure, Comedy, Family, Sci-Fi', 'Director': 'Brad Bird', 'Country': 'USA', 'Actors': 'Craig T. Nelson, Holly Hunter, Sarah Vowell, Huck Milner', 'RatingScore': '80', 'Type': 'movie'}
{'Title': 'Suspiria', 'Year': '2018', 'Rated': 'R', 'Runtime': '152 min', 'Genre': 'Fantasy, Horror, Mystery, Thriller', 'Director': 'Luca Guadagnino', 'Actors': 'Chloë Grace Moretz, Tilda Swinton, Doris Hick, Malgorzata Bela', 'Country': 'Italy, USA', 'RatingScore': '64', 'Type': 'movie'}
{'Title': 'A Quiet Place', 'Year': '2018', 'Rated': 'PG-13', 'Runtime': '90 min', 'Genre': 'Drama, Horror, Sci-Fi', 'Director': 'John Krasinski', 'Actors': 'Emily Blunt, John Krasinski, Millicent Simmonds, Noah Jupe', 'Country': 'USA', 'RatingScore': '82', 'Type': 'movie'}

From the parsed JSON data, print a list of the all of the movie titles, along with the duration of each movie.

In [26]:
import pandas as pd
wantedTitles = []
wantedDuration = []
for x in range(len(data)):
    wantedTitles.append(data[x]["Title"])
    wantedDuration.append(data[x]["Runtime"])
df = pd.DataFrame()
df["wantedTitles"] =wantedTitles
df["wantedDuration"] =wantedDuration
df

               wantedTitles wantedDuration
0         London Has Fallen         99 min
1                  Deadpool        108 min
2           Kung Fu Panda 3         95 min
3                   Spectre        148 min
4                  Brooklyn        111 min
5              The Revenant        156 min
6                      1917        119 min
7                     Joker        122 min
8                Uncut Gems        135 min
9                Knives Out        131 min
10  Jumanji: The Next Level        123 min
11                    Venom        112 min
12            Incredibles 2        118 min
13                 Suspiria        152 min
14            A Quiet Place         90 min

Extract the genre information for each movie.

In [27]:
wantedGenre = []
for x in range(len(data)):
    wantedGenre.append(data[x]["Genre"])
    
df["wantedGenre"] =wantedGenre
df

,wantedTitles,wantedDuration,wantedGenre
0,London Has Fallen,99 min,"Action, Crime, Thriller"
1,Deadpool,108 min,"Action, Adventure, Comedy"
2,Kung Fu Panda 3,95 min,"Animation, Action, Adventure"
3,Spectre,148 min,"Action, Adventure, Thriller"
4,Brooklyn,111 min,"Drama, Romance"
5,The Revenant,156 min,"Adventure, Drama, Thriller"
6,1917,119 min,"Drama, War"
7,Joker,122 min,"Crime, Drama, Thriller"
8,Uncut Gems,135 min,"Crime, Drama, Thriller"
9,Knives Out,131 min,"Comedy, Crime, Drama, Mystery, Thriller"
10,Jumanji: The Next Level,123 min,"Action, Adventure, Comedy, Fantasy"
11,Venom,112 min,"Action, Sci-Fi, Thriller"
12,Incredibles 2,118 min,"Animation, Action, Adventure, Comedy, Family, ..."
13,Suspiria,152 min,"Fantasy, Horror, Mystery, Thriller"
14,A Quiet Place,90 min,"Drama, Horror, Sci-Fi"

## Task 2 - XML Parsing

Use Python to download a file containing a contact list in XML format from the URL: http://mlg.ucd.ie/modules/COMP30760/contacts.xml

In [28]:
url = "http://mlg.ucd.ie/modules/COMP30760/contacts.xml"
response = urllib.request.urlopen(url)
raw_xml = response.read().decode()
print(raw_xml)

<?xml version="1.0"?>
<contacts>
  <contact>
    <name>John Smith</name>
    <phone>085-456-7890</phone>
    <email>johnsmith243@gmail.com</email>
  </contact>
  <contact>
    <name>Alice Murphy</name>
    <phone>086-456-7891</phone>
    <email>alice.murphy12@ucd.ie</email>
  </contact>
  <contact>
    <name>Joe Adams</name>
    <phone>086-222-4654</phone>
    <email>joeadams2016@tcd.ie</email>
  </contact>
  <contact>
    <name>Carol Conroy</name>
    <phone>087-131-1331</phone>
    <email>cconry1342@gmail.com</email>
  </contact>
  <contact>
    <name>Mary Carthy</name>
    <phone>086-221-7433</phone>
    <email>mcarthy1987@ucd.ie</email>
  </contact>
</contacts>

Parse the XML data that you have downloaded.

In [29]:
import xml.etree.ElementTree
tree = xml.etree.ElementTree.fromstring(raw_xml)

From the parsed XML data, extract the name, email address and phone number of each contact.

In [34]:
name = []
email = []
phone = []

for contact in tree.findall("contact"):
    name.append(contact.find("name").text)
    email.append(contact.find("email").text)
    phone.append(contact.find("phone").text)

df2 = pd.DataFrame()
df2["Name"] =name
df2["Email Address"] =email
df2["Phone Number"] =phone
df2

           Name           Email Address  Phone Number
0    John Smith  johnsmith243@gmail.com  085-456-7890
1  Alice Murphy   alice.murphy12@ucd.ie  086-456-7891
2     Joe Adams     joeadams2016@tcd.ie  086-222-4654
3  Carol Conroy    cconry1342@gmail.com  087-131-1331
4   Mary Carthy      mcarthy1987@ucd.ie  086-221-7433